# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WtbdRCS4EQ3NnuDI9mNdY2dArvAjzpCx
"""

import re
def normalize_text(text):
    text = text.lower()
    text = " ".join(text.split())
    text = re.sub(r'[^\w\s]', '', text)

    return text

input_text = "  SALOM, Bu yerda    ortiqcha bo'sh joylar va MAXSUS BELGILAR yoq! "
normalized_text = normalize_text(input_text)
print("Normallashgan matn:", normalized_text)